# Generated by Django 5.2.6 on 2025-09-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_active_driver',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_state',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='employee_number',
            field=models.CharField(default=1, help_text='Employee number', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
