# Generated by Django 5.2.6 on 2025-09-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_employee_id_remove_driver_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='driver',
            managers=[
            ],
        ),
    ]
