# Generated by Django 5.2.6 on 2025-09-15 20:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.JSONField(help_text="{'lat': float, 'lng': float, 'address': str}")),
                ('pickup_location', models.JSONField(help_text="{'lat': float, 'lng': float, 'address': str}")),
                ('dropoff_location', models.JSONField(help_text="{'lat': float, 'lng': float, 'address': str}")),
                ('current_cycle_hours', models.DecimalField(decimal_places=1, help_text='Current hours used in 8-day cycle', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Total distance in miles', max_digits=10, null=True)),
                ('estimated_duration', models.DurationField(blank=True, help_text='Estimated total trip duration', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planned_start_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, help_text='GeoJSON route geometry from mapping service', null=True)),
                ('is_hos_compliant', models.BooleanField(default=True)),
                ('hos_violations', models.JSONField(blank=True, help_text='List of HOS violations if any', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel Stop'), ('rest', 'Mandatory Rest'), ('break', 'Break')], max_length=20)),
                ('location', models.JSONField(help_text="{'lat': float, 'lng': float, 'address': str, 'name': str}")),
                ('planned_arrival_time', models.DateTimeField()),
                ('planned_departure_time', models.DateTimeField()),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Planned duration in minutes')),
                ('distance_from_previous', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Distance from previous stop in miles', max_digits=8)),
                ('is_mandatory', models.BooleanField(default=False, help_text='True for HOS-required stops')),
                ('notes', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
                'ordering': ['sequence'],
                'unique_together': {('trip', 'sequence')},
            },
        ),
    ]
